# Generated by Django 4.0.4 on 2022-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_remove_ads_address_ads_category_ads_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclass',
            old_name='lase_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
