# Generated by Django 4.0.4 on 2022-05-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
    ]
