# Generated by Django 4.0.4 on 2022-05-14 16:52

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[authentication.models.nine_years_old]),
        ),
    ]
