# Generated by Django 4.0.4 on 2022-05-14 16:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, null=True, validators=[authentication.models.no_rambler]),
        ),
    ]
